### ISSUE TITLE
`MAP_FAILED` breaks the build on OS X 10.10.2, Apple LLVM 6.1.0 (clang-602.0.53)

### ISSUE THREAD

**Issue by hausdorff** [BitFunnel/BitFunnel#233]
Confirmed after fresh clone (HEAS @ 1003dc7b9b76a7b1bcb2fd719ac7679ae627d1ea) and build. Breaks both the xcode and make builds. Running make produces an error like this:

```
[ 20%] Building CXX object src/Common/Utilities/src/CMakeFiles/Utilities.dir/AlignedBuffer.cpp.o
cd /Users/alex/src/bitFunnel/build-make/src/Common/Utilities/src && /usr/local/opt/ccache/libexec/g++    -I/Users/alex/src/bitFunnel/googletest/googletest/include -I/Users/alex/src/bitFunnel/inc -I/Users/alex/src/bitFunnel/src/Common/CmdLineParser/inc -I/Users/alex/src/bitFunnel/src/Common/CsvTsv/inc -I/Users/alex/src/bitFunnel/src/Common/Utilities/src  -msse4.2 -std=c++14 -Wall -Wextra -Werror -Wold-style-cast -O3 -DNDEBUG   -o CMakeFiles/Utilities.dir/AlignedBuffer.cpp.o -c /Users/alex/src/bitFunnel/src/Common/Utilities/src/AlignedBuffer.cpp
/Users/alex/src/bitFunnel/src/Common/Utilities/src/AlignedBuffer.cpp:66:29: error: use of old-style cast [-Werror,-Wold-style-cast]
        if (m_rawBuffer == ((void *)-1))
                            ^       ~~
1 error generated.
```

The compiler is saying that our strict no-C-style-casts flag doesn't allow us to have a C-style cast in our code. But, the problem is actually not that there is a C-style cast to `void *` in the actual source code. The actual code looks like this:

```
        if (m_rawBuffer == MAP_FAILED)
```

What's happening here turns out to be a well-known issue: `MAP_FAILED` on some platforms gets turned into a C-style cast. For example, in the Dart language, they solve this problem by [re-defining the macro](https://github.com/dart-lang/sdk/blob/master/runtime/vm/virtual_memory_macos.cc#L23) as a `reinterpret_cast`. I confirmed that this is really the problem by re-defining `MAP_FAILED` everywhere I found it. (Currently, 3 files: `AlignedBuffer.cpp`, `PackedArray.cpp`, and `SimpleBuffer.cpp`.)

Off the cuff, there are a few solutions to this problem, each in projects of good repute:
- Re-define `MAP_FAILED`. Because the uses of `MAP_FAILED` are constrained to .cpp files, this can be done either by creating a common header or by just re-defining it in ever .cpp file. Both are ugly; the second doesn't really prevent this from breaking the build again.
- Add something like `#pragma GCC diagnostic ignored "-Wold-style-cast"` to each use of `MAP_FAILED`. Also ugly, and does not prevent this from breaking the build again.
- Wrap `mmap` to abstract this problem away. Doesn't solve the problem of people forgetting to use the wrapper instead of normal `mmap`.

**Comment by hausdorff** [comment]
This is blocks building for me on OS X 10.10.2. Do people have thoughts about the proposals on the table?

**Comment by danluu** [comment]
I don't have a strong opinion on this. That being said, wrapping `mmap` seems like overkill to me because we only call `mmap` from a few libraries and don't ever really use it directly.

**Comment by MikeHopcroft** [comment]
I think we should just write, 

`if (m_rawBuffer == reinterpret_cast<void*>(-1))`

and add a comment saying why we're not using MAP_FAILED.

**Comment by hausdorff** [comment]
Ok, let's do that. But, just for my own education, why is hard-coding this in a safe bet? It's not part of the POSIX spec, so is there some sort of ABI compat thing that causes this to always be the value of `MAP_FAILED`?

**Comment by MikeHopcroft** [comment]
Whether we #undef MAP_FAILED and then redefine it or just use the reinterpret_cast<void*>(-1), we are hard coding a new value. This is why I recommend a comment. The only potentially better solution would be to put the reinterpret_cast<void*>(-1) inside an #ifdef that checks for versions of OSX that don't properly implement MAP_FAILED. The problem with this solution is that it might need a brittle #ifdef expression or changes to the CMakeLists.txt files. We should probably open a separate issue to revert this change once we decide that we're no longer supporting OSX versions below 11.

**Comment by danluu** [comment]
BTW, it might be possible to support older versions of OS X by requiring that people `brew install llvm38` or something similar.

**Comment by MikeHopcroft** [comment]
One other possibility, if we're uncomfortable using -1, is to suppress the warning in the source file around the line in question. This would allow us to retain the MAP_FAILED while still addressing the problem on older OSX development environments.

**Comment by danluu** [comment]
I think this was fixed a month ago?
